language: node_js

cache:
  yarn: true
  directories:
    - ~/.cache
  override:
    - yarn install --frozen-lockfile

defaults: &verify
  install:
    - yarn
    - yarn bootstrap

jobs:
  include:
    # Verify on push
    - stage: Verify
      if: type = push
      <<: *verify
      env:
        - SHA=$TRAVIS_COMMIT
      script:
        - node ./scripts/lint.js
    - stage: Verify
      if: type = push
      <<: *verify
      env:
        - NODE_ENV=test
        - SHA=$TRAVIS_COMMIT
      script:
        - node ./scripts/run-tests.js

    # Verify on pull request
    - stage: Verify
      if: type = pull_request
      <<: *verify
      env:
        - SHA=$TRAVIS_PULL_REQUEST_SHA
      script:
        - node ./scripts/lint.js
    - stage: Verify
      if: type = pull_request
      <<: *verify
      env:
        - NODE_ENV=test
        - SHA=$TRAVIS_PULL_REQUEST_SHA
      script:
        - node ./scripts/run-tests.js
